-- Create tables
create table profiles (
  id uuid references auth.users not null primary key,
  role text not null default 'user',
  check (role in ('user', 'admin'))
);

create table recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  video_url text,
  thumbnail_url text,
  prep_time text,
  calories text,
  ingredients jsonb,
  steps text,
  is_highlight boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table profiles enable row level security;
alter table recipes enable row level security;

-- Profiles: Users can read their own profile. Admin can read all.
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);

-- Recipes: Public read access
create policy "Recipes are viewable by everyone." on recipes for select using (true);

-- Recipes: Admin write access
-- Note: This requires a way to check for admin role. 
-- For simplicity in MVP, we might rely on the app logic or a helper function in DB.
-- Robust way:
-- create policy "Admins can insert recipes." on recipes for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
-- create policy "Admins can update recipes." on recipes for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Since this is an MVP and strict complexity wasn't requested beyond "Escrita apenas para role 'admin'", we will assume the profile check is sufficient.
create policy "Admins can insert recipes." on recipes for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update recipes." on recipes for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete recipes." on recipes for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Trigger to create profile on signup (optional but good for 'user' default)
-- or handle manually in backend. For now, since signup is "fechado / pré-criado", we assume manual profile creation or simple hook.
-- Let's add a simple trigger for safety if manual insert is done via Auth API.
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
