-- Create tags table
create table tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create recipe_tags join table
create table recipe_tags (
  recipe_id bigint references recipes(id) on delete cascade not null,
  tag_id bigint references tags(id) on delete cascade not null,
  primary key (recipe_id, tag_id)
);

-- Enable RLS
alter table tags enable row level security;
alter table recipe_tags enable row level security;

-- Policies for Tags
-- Everyone can read tags
create policy "Tags are viewable by everyone." on tags for select using (true);
-- Only admins can insert/update/delete tags (optional, for now maybe just insert via seed or future admin logic)
create policy "Admins can insert tags." on tags for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update tags." on tags for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete tags." on tags for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Policies for Recipe Tags
-- Everyone can read recipe tags
create policy "Recipe tags are viewable by everyone." on recipe_tags for select using (true);
-- Only admins can manage recipe tags (linked to recipe editing)
create policy "Admins can insert recipe_tags." on recipe_tags for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete recipe_tags." on recipe_tags for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Seed default tags
insert into tags (name) values 
('Saudável'), 
('Vegetariano'), 
('Vegano'), 
('Sem Glúten'), 
('Sem Lactose'), 
('Rápido'), 
('Doce'), 
('Salgado'), 
('Café da Manhã'), 
('Low Carb')
on conflict (name) do nothing;
