-- ============================================================
-- MIGRATION: Tags → Categories + Subcategories
-- Execute this in the Supabase SQL Editor
-- ============================================================

-- ============================================================
-- STEP 1: Rename existing tables
-- ============================================================

-- Rename tags → subcategories
ALTER TABLE tags RENAME TO subcategories;

-- Rename recipe_tags → recipe_subcategories
ALTER TABLE recipe_tags RENAME TO recipe_subcategories;

-- Rename the FK column in recipe_subcategories
ALTER TABLE recipe_subcategories RENAME COLUMN tag_id TO subcategory_id;

-- ============================================================
-- STEP 2: Drop old RLS policies (they reference old table names)
-- ============================================================

-- Drop old tags policies
DROP POLICY IF EXISTS "Tags are viewable by everyone." ON subcategories;
DROP POLICY IF EXISTS "Admins can insert tags." ON subcategories;
DROP POLICY IF EXISTS "Admins can update tags." ON subcategories;
DROP POLICY IF EXISTS "Admins can delete tags." ON subcategories;

-- Drop old recipe_tags policies
DROP POLICY IF EXISTS "Recipe tags are viewable by everyone." ON recipe_subcategories;
DROP POLICY IF EXISTS "Admins can insert recipe_tags." ON recipe_subcategories;
DROP POLICY IF EXISTS "Admins can delete recipe_tags." ON recipe_subcategories;

-- ============================================================
-- STEP 3: Create new RLS policies for renamed tables
-- ============================================================

-- Subcategories policies
CREATE POLICY "Subcategories are viewable by everyone." ON subcategories FOR SELECT USING (true);
CREATE POLICY "Admins can insert subcategories." ON subcategories FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can update subcategories." ON subcategories FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can delete subcategories." ON subcategories FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Recipe_subcategories policies
CREATE POLICY "Recipe subcategories are viewable by everyone." ON recipe_subcategories FOR SELECT USING (true);
CREATE POLICY "Admins can insert recipe_subcategories." ON recipe_subcategories FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can delete recipe_subcategories." ON recipe_subcategories FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ============================================================
-- STEP 4: Create categories table
-- ============================================================

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Categories are viewable by everyone." ON categories FOR SELECT USING (true);
CREATE POLICY "Admins can insert categories." ON categories FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can update categories." ON categories FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can delete categories." ON categories FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ============================================================
-- STEP 5: Create category_subcategories join table
-- ============================================================

CREATE TABLE category_subcategories (
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
  subcategory_id BIGINT REFERENCES subcategories(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (category_id, subcategory_id)
);

ALTER TABLE category_subcategories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Category subcategories are viewable by everyone." ON category_subcategories FOR SELECT USING (true);
CREATE POLICY "Admins can insert category_subcategories." ON category_subcategories FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can delete category_subcategories." ON category_subcategories FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ============================================================
-- STEP 6: Create recipe_categories join table
-- ============================================================

CREATE TABLE recipe_categories (
  recipe_id BIGINT REFERENCES recipes(id) ON DELETE CASCADE NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (recipe_id, category_id)
);

ALTER TABLE recipe_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Recipe categories are viewable by everyone." ON recipe_categories FOR SELECT USING (true);
CREATE POLICY "Admins can insert recipe_categories." ON recipe_categories FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can delete recipe_categories." ON recipe_categories FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ============================================================
-- STEP 7: Seed categories
-- ============================================================

INSERT INTO categories (name) VALUES
  ('Jantares'),
  ('Almoços'),
  ('Café da Manhã'),
  ('Bolos sem Glúten'),
  ('Doces sem Açúcar'),
  ('Introdução Alimentar'),
  ('Receitinhas para Crianças')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- STEP 8: Link categories to subcategories
-- ============================================================

-- Helper: get subcategory ID by name
-- We use a DO block for clarity

DO $$
DECLARE
  cat_jantares BIGINT;
  cat_almocos BIGINT;
  cat_cafe BIGINT;
  cat_bolos BIGINT;
  cat_doces BIGINT;
  cat_intro BIGINT;
  cat_criancas BIGINT;
BEGIN
  SELECT id INTO cat_jantares FROM categories WHERE name = 'Jantares';
  SELECT id INTO cat_almocos FROM categories WHERE name = 'Almoços';
  SELECT id INTO cat_cafe FROM categories WHERE name = 'Café da Manhã';
  SELECT id INTO cat_bolos FROM categories WHERE name = 'Bolos sem Glúten';
  SELECT id INTO cat_doces FROM categories WHERE name = 'Doces sem Açúcar';
  SELECT id INTO cat_intro FROM categories WHERE name = 'Introdução Alimentar';
  SELECT id INTO cat_criancas FROM categories WHERE name = 'Receitinhas para Crianças';

  -- Jantares: Saudável, Vegetariano, Vegano, Sem Glúten, Sem Lactose, Low Carb, Salgado, Rápido
  INSERT INTO category_subcategories (category_id, subcategory_id)
  SELECT cat_jantares, id FROM subcategories WHERE name IN ('Saudável', 'Vegetariano', 'Vegano', 'Sem Glúten', 'Sem Lactose', 'Low Carb', 'Salgado', 'Rápido')
  ON CONFLICT DO NOTHING;

  -- Almoços: Saudável, Vegetariano, Vegano, Sem Glúten, Sem Lactose, Low Carb, Salgado, Rápido
  INSERT INTO category_subcategories (category_id, subcategory_id)
  SELECT cat_almocos, id FROM subcategories WHERE name IN ('Saudável', 'Vegetariano', 'Vegano', 'Sem Glúten', 'Sem Lactose', 'Low Carb', 'Salgado', 'Rápido')
  ON CONFLICT DO NOTHING;

  -- Café da Manhã: todas as subcategorias
  INSERT INTO category_subcategories (category_id, subcategory_id)
  SELECT cat_cafe, id FROM subcategories WHERE name IN ('Saudável', 'Vegetariano', 'Vegano', 'Sem Glúten', 'Sem Lactose', 'Rápido', 'Doce', 'Salgado', 'Café da Manhã', 'Low Carb')
  ON CONFLICT DO NOTHING;

  -- Bolos sem Glúten: Sem Glúten, Doce, Vegetariano, Vegano, Sem Lactose
  INSERT INTO category_subcategories (category_id, subcategory_id)
  SELECT cat_bolos, id FROM subcategories WHERE name IN ('Sem Glúten', 'Doce', 'Vegetariano', 'Vegano', 'Sem Lactose')
  ON CONFLICT DO NOTHING;

  -- Doces sem Açúcar: Doce, Saudável, Low Carb, Vegetariano, Vegano, Sem Glúten, Sem Lactose
  INSERT INTO category_subcategories (category_id, subcategory_id)
  SELECT cat_doces, id FROM subcategories WHERE name IN ('Doce', 'Saudável', 'Low Carb', 'Vegetariano', 'Vegano', 'Sem Glúten', 'Sem Lactose')
  ON CONFLICT DO NOTHING;

  -- Introdução Alimentar: Saudável, Sem Glúten, Sem Lactose, Rápido
  INSERT INTO category_subcategories (category_id, subcategory_id)
  SELECT cat_intro, id FROM subcategories WHERE name IN ('Saudável', 'Sem Glúten', 'Sem Lactose', 'Rápido')
  ON CONFLICT DO NOTHING;

  -- Receitinhas para Crianças: Saudável, Rápido, Doce, Salgado, Sem Glúten, Sem Lactose
  INSERT INTO category_subcategories (category_id, subcategory_id)
  SELECT cat_criancas, id FROM subcategories WHERE name IN ('Saudável', 'Rápido', 'Doce', 'Salgado', 'Sem Glúten', 'Sem Lactose')
  ON CONFLICT DO NOTHING;
END $$;
